package com.compliance.db.compliance_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE ComplianceBase PLEASE EDIT ../Compliance.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Compliance object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;

import org.springframework.jdbc.core.RowMapper;
import com.compliance.db.compliance_db.entity.Compliance;

public class ComplianceBase implements RowMapper<Compliance>{
	
	private Long _id;
	
	// Attributes
    private Date approvedDate;
    private String aprroverName;
    private String compliance_id;
    private String createdBy;
    private Date createdDate;
    private Boolean isactive;
    private String lawType;
    private String penalty;
    private String publishedBy;
    private Date publishedOn;
    private String regulator;
    private String section;
    private String status;
    private String version;
	
	
	
	@Override
	public Compliance mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Compliance obj = new Compliance();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setApprovedDate(rs.getDate("approvedDate"));
			obj.setAprroverName(rs.getString("aprroverName"));
			obj.setCompliance_id(rs.getString("compliance_id"));
			obj.setCreatedBy(rs.getString("createdBy"));
			obj.setCreatedDate(rs.getDate("createdDate"));
			obj.setIsactive(rs.getBoolean("isactive"));
			obj.setLawType(rs.getString("lawType"));
			obj.setPenalty(rs.getString("penalty"));
			obj.setPublishedBy(rs.getString("publishedBy"));
			obj.setPublishedOn(rs.getDate("publishedOn"));
			obj.setRegulator(rs.getString("regulator"));
			obj.setSection(rs.getString("section"));
			obj.setStatus(rs.getString("status"));
			obj.setVersion(rs.getString("version"));
			
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public Date getApprovedDate() {
		return approvedDate;
	}


	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}
	public String getAprroverName() {
		return aprroverName;
	}


	public void setAprroverName(String aprroverName) {
		this.aprroverName = aprroverName;
	}
	public String getCompliance_id() {
		return compliance_id;
	}


	public void setCompliance_id(String compliance_id) {
		this.compliance_id = compliance_id;
	}
	public String getCreatedBy() {
		return createdBy;
	}


	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public Date getCreatedDate() {
		return createdDate;
	}


	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Boolean getIsactive() {
		return isactive;
	}


	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}
	public String getLawType() {
		return lawType;
	}


	public void setLawType(String lawType) {
		this.lawType = lawType;
	}
	public String getPenalty() {
		return penalty;
	}


	public void setPenalty(String penalty) {
		this.penalty = penalty;
	}
	public String getPublishedBy() {
		return publishedBy;
	}


	public void setPublishedBy(String publishedBy) {
		this.publishedBy = publishedBy;
	}
	public Date getPublishedOn() {
		return publishedOn;
	}


	public void setPublishedOn(Date publishedOn) {
		this.publishedOn = publishedOn;
	}
	public String getRegulator() {
		return regulator;
	}


	public void setRegulator(String regulator) {
		this.regulator = regulator;
	}
	public String getSection() {
		return section;
	}


	public void setSection(String section) {
		this.section = section;
	}
	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}
	public String getVersion() {
		return version;
	}


	public void setVersion(String version) {
		this.version = version;
	}
	
    
    
    
    
}